dependency:
  - board_motor_control_phase_voltage_sampling

excluded_targets:
  - flash_sdram_xip_release
  - flash_sdram_xip
  - flash_xip_release
  - flash_uf2_release
  - release
  - flash_sdram_uf2
  - flash_sdram_uf2_release
